BoPlats/Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BoPlats.Models
{
    public class Apartment
    {
        [DisplayName("[Apartment ID]")]
        public int Id { get; set; }

        [Required,StringLength(50),DisplayName("Adress")]    
        public string Adress { get; set; }
                
        [DisplayName("Elevator")]
        public bool Elevator { get; set; }
      
        [StringLength(10)]
        [Required]
        [DisplayName("Rooms")]
        public string NumberOfRooms { get; set; }
       
        [DisplayName("Balcony")]
        public bool Balcony { get; set; }
       
        [Required]
        [DisplayName("Squaremeter")]
        public string SquareMeter { get; set; }
        [Required]
        [DisplayName("Floor")]
        public string Floor { get; set; }

        [Required]
        [DisplayName("Monthly Cost")]
        public string Rent { get; set; }
        
      //time 
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        private DateTime _date = DateTime.Now;

        [DisplayName("Time/Date")]
        [DataType(DataType.DateTime)]
        public DateTime RegisterTime
        {                          
            get { return _date; }
            set { _date = value; }
        }

        
        //relation

        public IList<Apply> Apply { get; set; }

    }
}

BoPlats/Controllers/ApartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoPlats.Models;

namespace BoPlats.Controllers
{
    public class ApartmentsController : Controller
    {
        private readonly DataContext_Milad _context;

        public ApartmentsController(DataContext_Milad context)
        {
            _context = context;
        }

        // GET: Apartments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Apartment.ToListAsync());
        }

        // GET: Apartments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apartment = await _context.Apartment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (apartment == null)
            {
                return NotFound();
            }

            return View(apartment);
        }

        // GET: Apartments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Apartments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Adress,Elevator,NumberOfRooms,Balcony,SquareMeter,Floor,Rent,RegisterTime")] Apartment apartment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(apartment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(apartment);
        }

        // GET: Apartments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apartment = await _context.Apartment.FindAsync(id);
            if (apartment == null)
            {
                return NotFound();
            }
            return View(apartment);
        }

        // POST: Apartments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Adress,Elevator,NumberOfRooms,Balcony,SquareMeter,Floor,Rent,RegisterTime")] Apartment apartment)
        {
            if (id != apartment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(apartment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApartmentExists(apartment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(apartment);
        }

        // GET: Apartments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apartment = await _context.Apartment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (apartment == null)
            {
                return NotFound();
            }

            return View(apartment);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var apartment = await _context.Apartment.FindAsync(id);
            _context.Apartment.Remove(apartment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApartmentExists(int id)
        {
            return _context.Apartment.Any(e => e.Id == id);
        }
    }
}

BoPlats/Views/Apartments/Create.cshtml
@model BoPlats.Models.Apartment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Apartment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Elevator" /> @Html.DisplayNameFor(model => model.Elevator)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfRooms" class="control-label"></label>
                <input asp-for="NumberOfRooms" class="form-control" />
                <span asp-validation-for="NumberOfRooms" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Balcony" /> @Html.DisplayNameFor(model => model.Balcony)
                </label>
            </div>



            <div class="form-group">
                <label asp-for="SquareMeter" class="control-label"></label>
                <input asp-for="SquareMeter" class="form-control" />
                <span asp-validation-for="SquareMeter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rent" class="control-label"></label>
                <input asp-for="Rent" class="form-control" />
                <span asp-validation-for="Rent" class="text-danger"></span>
            </div>
       
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BoPlats/Views/Apartments/Delete.cshtml
@model BoPlats.Models.Apartment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Apartment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Elevator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Elevator)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfRooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfRooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balcony)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balcony)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SquareMeter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SquareMeter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Floor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Floor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BoPlats/Views/Apartments/Details.cshtml
@model BoPlats.Models.Apartment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Apartment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Elevator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Elevator)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfRooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfRooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balcony)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balcony)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SquareMeter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SquareMeter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Floor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Floor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BoPlats/Views/Apartments/Edit.cshtml
@model BoPlats.Models.Apartment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Apartment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Elevator" /> @Html.DisplayNameFor(model => model.Elevator)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfRooms" class="control-label"></label>
                <input asp-for="NumberOfRooms" class="form-control" />
                <span asp-validation-for="NumberOfRooms" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Balcony" /> @Html.DisplayNameFor(model => model.Balcony)
                </label>
            </div>>
            <div class="form-group">
                <label asp-for="SquareMeter" class="control-label"></label>
                <input asp-for="SquareMeter" class="form-control" />
                <span asp-validation-for="SquareMeter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rent" class="control-label"></label>
                <input asp-for="Rent" class="form-control" />
                <span asp-validation-for="Rent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisterTime" class="control-label"></label>
                <input asp-for="RegisterTime" class="form-control" />
                <span asp-validation-for="RegisterTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BoPlats/Views/Apartments/Index.cshtml
@model IEnumerable<BoPlats.Models.Apartment>

@{
    ViewData["Title"] = "Index";
}



<div class="jumbotron text-center">
    <p class="lead">Avaiable apartments for rent</p>
    <p><a class="btn btn-lg btn-success" asp-area="" asp-controller="Apartments" asp-action="Create" role="button">Register Apartment for rental</a></p>


    <table class="table">
        <thead>
            <tr>
                <th>
                    Post Info
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Adress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Elevator)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumberOfRooms)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Balcony)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SquareMeter)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Floor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Rent)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>


            @foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        <div class="row text-center">
                            <p>
                                Id: @Html.DisplayFor(modelItem => item.Id)
                            </p>
                        </div>
                        <div class="row text-center">
                            Time: @Html.DisplayFor(modelItem => item.RegisterTime)
                        </div>

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Adress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Elevator)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberOfRooms)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Balcony)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SquareMeter)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Floor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rent)
                    </td>


                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>